plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

repositories {
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"hypothermia_core" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

tasks.register('copyToModrinth') {
    doLast {
        def modsFolder = "D:\\Users\\Zevaldo\\AppData\\Roaming\\ModrinthApp\\profiles\\Hypothermia 2\\mods"
        def jarFile = tasks.remapJar.archiveFile.get().asFile
        if (jarFile.exists()) {
            copy {
                from jarFile
                into modsFolder
            }
            println "Successfully copied ${jarFile.name} to ${modsFolder}"
        } else {
            println "Remapped jar file not found, run 'remapJar' task first."
        }
    }
}

build.finalizedBy('copyToModrinth')

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
	repositories {
	}
}
